WHITESPACE = frozenset({" ", "\n", "\t"})
DIGITS = frozenset({"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ""})
DECIMAL_POINT = "."
PLUS = "+"
MINUS = "-"
MULTIPLY = "*"
DIVIDE = "/"
LEFT_PAREN = "("
RIGHT_PAREN = ")"
